### ISSUE TITLE
Web interface works with bugs starting with 0.1.72

### ISSUE THREAD

**Issue by Dim0N22** [elgatito/elementum#32]
After the latest update to 0.1.72 web interface partially stopped working for me.

Symptoms:

1. I can navigate to http://<my_ip>:65220/web/ to get the template html file
2. It requests a list of active torrents by calling http://<my_ip>:65220/torrents/list
3. According to Chrome network monitoring, `torrents/list` never responds
4. Ultimately after a lot of time the list of active torrents is loaded but the status column is empty (no status shown at all)
5. Elementum at this point appears to be in some semi-broken state

Rollback to 0.1.71 fixes the problem.

I suspect something was changed that affects API, probably [this commit](https://github.com/elgatito/elementum/commit/93e33ef40e3291fa2fe86169415016b2af187f1a).

Error log:
```2021-03-21 18:26:46.043 T:3184362368   ERROR: Traceback (most recent call last):
2021-03-21 18:26:46.043 T:3184362368   ERROR:   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 304, in run
2021-03-21 18:26:46.044 T:3184362368   ERROR:     data = _json(url)
2021-03-21 18:26:46.044 T:3184362368   ERROR:   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 166, in _json
2021-03-21 18:26:46.044 T:3184362368   ERROR:     with closing(urllib_request.urlopen(url)) as response:
2021-03-21 18:26:46.044 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
2021-03-21 18:26:46.044 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
2021-03-21 18:26:46.044 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
2021-03-21 18:26:46.044 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/httplib.py", line 438, in begin
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
2021-03-21 18:26:46.045 T:3184362368   ERROR:   File "/usr/lib/python2.7/socket.py", line 480, in readline
2021-03-21 18:26:46.045 T:3184362368   ERROR: timeout: timed out
2021-03-21 18:26:46.047 T:3184362368   ERROR: [plugin.video.elementum] Traceback (most recent call last):
2021-03-21 18:26:46.047 T:3184362368   ERROR: [plugin.video.elementum]   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 304, in run
2021-03-21 18:26:46.048 T:3184362368   ERROR: [plugin.video.elementum]     data = _json(url)
2021-03-21 18:26:46.048 T:3184362368   ERROR: [plugin.video.elementum]   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 166, in _json
2021-03-21 18:26:46.048 T:3184362368   ERROR: [plugin.video.elementum]     with closing(urllib_request.urlopen(url)) as response:
2021-03-21 18:26:46.049 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
2021-03-21 18:26:46.049 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 429, in open
2021-03-21 18:26:46.049 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
2021-03-21 18:26:46.050 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2021-03-21 18:26:46.050 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
2021-03-21 18:26:46.050 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
2021-03-21 18:26:46.050 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
2021-03-21 18:26:46.051 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 438, in begin
2021-03-21 18:26:46.051 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
2021-03-21 18:26:46.051 T:3184362368   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/socket.py", line 480, in readline
2021-03-21 18:26:46.052 T:3184362368   ERROR: [plugin.video.elementum] timeout: timed out```

**Comment by Dim0N22** [comment]
Works for me now, thanks!
