### ISSUE TITLE
Torrent search is broken

### ISSUE THREAD

**Issue by danryu** [elgatito/elementum#53]
On up-to-date Ubuntu 21.04 x64.

Seems to be a libffi version mismatch runtime/build-time.
Elementum 0.1.77
Elementum Burst 0.0.67

-----

```
2021-05-22 12:02:36.537 T:642854   FATAL <general>: [script.elementum.burst] 'https://www.xyz.to/search/thing+1991/1/' failed with SystemError("ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)"):
2021-05-22 12:02:36.540 T:642854   ERROR <general>: Exception in thread 
2021-05-22 12:02:36.540 T:642854   ERROR <general>: Thread-1
2021-05-22 12:02:36.540 T:642854   ERROR <general>: :
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>: Traceback (most recent call last):
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>:   File "/home/vebb/.kodi/addons/script.elementum.burst/burst/burst.py", line 260, in extract_torrents
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>:     
2021-05-22 12:02:36.540 T:642854   ERROR <general>: raise StopIteration
2021-05-22 12:02:36.540 T:642854   ERROR <general>: 
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>: StopIteration
2021-05-22 12:02:36.540 T:642854   ERROR <general>: 
2021-05-22 12:02:36.540 T:642854   ERROR <general>: 
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>: 
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>: Traceback (most recent call last):
                                                   
2021-05-22 12:02:36.540 T:642854   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:     
2021-05-22 12:02:36.541 T:642854   ERROR <general>: self.run()
2021-05-22 12:02:36.541 T:642854   ERROR <general>: 
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 892, in run
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:     
2021-05-22 12:02:36.541 T:642854   ERROR <general>: self._target(*self._args, **self._kwargs)
2021-05-22 12:02:36.541 T:642854   ERROR <general>: 
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:   File "/home/vebb/.kodi/addons/script.elementum.burst/burst/burst.py", line 645, in run_provider
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:     
2021-05-22 12:02:36.541 T:642854   ERROR <general>: results = process(provider=provider, generator=extract_torrents, filtering=filterInstance, has_special=payload['has_special'], skip_auth=payload['skip_auth'], start_time=start_time, timeout=timeout)
2021-05-22 12:02:36.541 T:642854   ERROR <general>: 
                                                   
2021-05-22 12:02:36.541 T:642854   ERROR <general>:   File "/home/vebb/.kodi/addons/script.elementum.burst/burst/provider.py", line 320, in process

```

**Comment by antonsoroko** [comment]
@danryu 

hi.
1) if issue looks like about burst - it should be created in burst repo.
2) it actually looks like not burst but kodi's python issue

what version of kodi do you use?

i just have updated my ubuntu 20.10 to 21.04 - everything works fine.

but i use kodi from ppa - 19.1
and looks like in main ubuntu repo it is still 19.0

please check your kodi installation and maybe update it.

**Comment by elgatito** [comment]
@danryu If you believe there is an issue with Burst. Create in appropriate repository. https://github.com/elgatito/script.elementum.burst/

**Comment by danryu** [comment]
> @danryu
>     1. if issue looks like about burst - it should be created in burst repo.
>     2. it actually looks like not burst but kodi's python issue
> what version of kodi do you use?
> i just have updated my ubuntu 20.10 to 21.04 - everything works fine.
> but i use kodi from ppa - 19.1
> and looks like in main ubuntu repo it is still 19.0
> but i guess you have kodi that was compiled not for 21.04
> please check your kodi installation and maybe update it.

Hi @antonsoroko 
I just purged my kodi installation and removed .kodi dir.
I installed 19.1 from PPA: ppa:team-xbmc/ppa

No change! Still 
` failed with SystemError("ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)"):
`
on every Torrent search.

Version recap:

- Ubuntu 21.04 x64 
- Elementum 0.1.77
- Elementum Burst 0.0.67
- Python 3.9.4-1
- Kodi 19.1

(My whole installation is completely vanilla, AFAIK)

@elgatito I have no idea where the root cause is. I will open the same bug in Burst repo if you think that would be more productive.

**Comment by antonsoroko** [comment]
>I will open the same bug in Burst repo if you think that would be more productive.

yes, please.
also please create a full log file http://elementum.surge.sh/contribute/log/
