### ISSUE TITLE
Fix concurrent map writes

### ISSUE THREAD

**Issue by elgatito** [elgatito/elementum#6]
```
16:36:52.404 T:3570398112  NOTICE: [plugin.video.elementum] INFO  torrentfs    ▶ GetTorrentForPath  [[0mOpening /Dennis.the.Menace.1993.720p.WEB-DL.DUB.2xMVO.2xAVO.ENG.SUB.mkv
16:36:52.405 T:3570398112  NOTICE: [plugin.video.elementum] [[32mNOTI  torrentfs    ▶ GetTorrentForPath  [[0m/Dennis.the.Menace.1993.720p.WEB-DL.DUB.2xMVO.2xAVO.ENG.SUB.mkv belongs to torrent Dennis.the.Menace.1993.720p.WEB-DL.DUB.2xMV
O.2xAVO.ENG.SUB.mkv
16:36:52.405 T:3570398112  NOTICE: [plugin.video.elementum] [[36mDEBU  bittorrent   ▶ NewFileReader    [[0mNewReader: 978003375
16:36:52.406 T:3570398112  NOTICE: [plugin.video.elementum] fatal error: concurrent map writes
16:36:52.411 T:3570398112  NOTICE: [plugin.video.elementum]
16:36:52.412 T:3570398112  NOTICE: [plugin.video.elementum] goroutine 43937 [running]:
16:36:52.412 T:3570398112  NOTICE: [plugin.video.elementum] runtime.throw(0xaf07de, 0x15)
16:36:52.413 T:3570398112  NOTICE: [plugin.video.elementum]     /usr/local/go/src/runtime/panic.go:605 +0x70 fp=0x1dc56b38 sp=0x1dc56b2c pc=0x442c0
16:36:52.413 T:3570398112  NOTICE: [plugin.video.elementum] runtime.mapassign_fast32(0x9ead18, 0x11b448e0, 0x3a4b25af, 0x22ea9290)
16:36:52.413 T:3570398112  NOTICE: [plugin.video.elementum]     /usr/local/go/src/runtime/hashmap_fast.go:431 +0x43c fp=0x1dc56b78 sp=0x1dc56b38 pc=0x23e80
16:36:52.414 T:3570398112  NOTICE: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.NewFileReader(0x1297e000, 0x11c95300, 0x1fc113e0, 0x3, 0x2, 0x2, 0x2104a480)
16:36:52.414 T:3570398112  NOTICE: [plugin.video.elementum]     /ext-go/1/src/github.com/elgatito/elementum/bittorrent/file_reader.go:38 +0x2dc fp=0x1dc56c00 sp=0x1dc56b78 pc=0x7726d4
16:36:52.415 T:3570398112  NOTICE: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.GetTorrentForPath(0x11bd2600, 0x11f640e0, 0x12, 0x1fc113ea, 0x3f, 0x1fc48f00, 0x755bc, 0x22f17c, 0xfe43d0)
16:36:52.416 T:3570398112  NOTICE: [plugin.video.elementum]     /ext-go/1/src/github.com/elgatito/elementum/bittorrent/torrentfs.go:65 +0x2e0 fp=0x1dc56ccc sp=0x1dc56c00 pc=0x7843c4
16:36:52.416 T:3570398112  NOTICE: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.ServeTorrent.func1(0xfa9418, 0x21aac7e0, 0x1fc48f00)
16:36:52.416 T:3570398112  NOTICE: [plugin.video.elementum]     /ext-go/1/src/github.com/elgatito/elementum/bittorrent/torrentfs.go:26 +0xb4 fp=0x1dc56d6c sp=0x1dc56ccc pc=0x7875c8
16:36:52.417 T:3570398112  NOTICE: [plugin.video.elementum] net/http.HandlerFunc.ServeHTTP(0x11c8dc80, 0xfa9418, 0x21aac7e0, 0x1fc48f00)

```

**Comment by elgatito** [comment]
Should be fixed in 0.0.44.
